### ISSUE TITLE
Singularity image

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [TRON-Bioinformatics/EasyFuse#1]
Hi @patricksorn @ibn-salem ,

Is there any plan for Singularity image as docker is not the usual option for most of the cluster systems? A singularity image would be very helpful.

Thanks.
Gurpreet

**Comment by patricksorn** [comment]
Hi @gurpreet-bioinfo ,

in the future we a Singularity image besides the Docker image will be a good solution, but in the meantime there is also the possibility to import the Docker image into the Singularity environment. We will put some documentation on the Wiki page how to do so.

Best regards,
Patrick

**Comment by gurpreet-bioinfo** [comment]
Thank you @patricksorn ! Would appreciate that. :-)

**Comment by ibn-salem** [comment]
Dear @gurpreet-bioinfo, 

we just released EasyFuse in version 1.3.6 which should resolve the issues with singularity. Please give it try and let us know here if it works for you. You can find instructions in the README.

Thanks,
Jonas
