### ISSUE TITLE
Read counts from detected tools are not annotated correctly

### ISSUE THREAD

**Issue by ibn-salem** [TRON-Bioinformatics/EasyFuse#21]
The output tables of the current version 1.3.6 contain zero read counts for tools that actually detected the fusion. This was likely introduced in the updated annotation code from version 1.3.6.

**Comment by jrouhana** [comment]
Hi @ibn-salem ,

Please see this: 

https://github.com/TRON-Bioinformatics/EasyFuse/issues/24

**Comment by ibn-salem** [comment]
This is fixed in version 1.3.7.
