### ISSUE TITLE
Tool runtime

### ISSUE THREAD

**Issue by BGI2016** [TRON-Bioinformatics/EasyFuse#22]
Hello @ibn-salem @priesgo @ozlemmuslu @martinloewer @mostafiz2010
My data is 260 million distinct sequencing reads（2×150 nt）.When I predicted GFs with the Easyfuse 1.3.6 from my data, the software ran for eight days. why run time is so long?Hope to get your reply.

Kind Regards,
Lily

**Comment by Tesson98** [comment]
Hi @ibn-salem @priesgo @ozlemmuslu @martinloewer  @mostafiz2010 

I have also met this problem with paried rna-seq fastq.gz files of 29 samples(2 * ~3G * 29samples).
Within them 24/29 succeed in the output but the remaining 5 samples were stuck in the soapfuse  prediction step (4 samples, succeed in upstream prediction steps) or in the fetchdata step ( 1 sample, succeed in upstream steps).
I have to ended related slurm jobs while running for 7 days. Could you help me with this problem？

Really glad to get your replies.
If you want more detailed information please just contact me.
Thank you so much!

Best regards,
Tesson

**Comment by whiffen-cann** [comment]
![1665473447849](https://user-images.githubusercontent.com/12433724/195024017-636f84a0-3c60-4d52-b69d-f85f368d7ecc.png)

@Tesson98 @priesgo 
I also encounter the same problem. When I use Docker to run EasyFuse, I always report an error in the fetchdata.py step.

**Comment by pintoa1-mskcc** [comment]
I also encounter extremely long run times, and then soapfuse will die randomly....

**Comment by ibn-salem** [comment]
The runtime should be improved in the latest EasyFuse versions. If not please open a new issue. Thanks.
