### ISSUE TITLE
install and run locally 

### ISSUE THREAD

**Issue by whiffen-cann** [TRON-Bioinformatics/EasyFuse#27]
Can this pipeline be installed and run locally now ? I have installed all tools required and dependencies ,but I donot know how to run locally~
I know the easyfuse  repository has shown the way to run locally, but I don't know if it still supports the way .
Could you show me again ? 
 
When I run with docker ,my samples always stucked in fetch.py step ， so I may try to run locally  for easy debug .

**Comment by ibn-salem** [comment]
Hi, this should be resolved with nextflow and conda support in the latest EasyFuse versions.
