### ISSUE TITLE
Request access to the model with smaller feature sets that operate independently of the prediction tools

### ISSUE THREAD

**Issue by PubuduSaneth** [TRON-Bioinformatics/EasyFuse#28]
Hi,
Thank you very much for developing and maintaining `EasyFuse`.  I looked into features used in the model `Fusion_modeling_FFPE_train_v33.random_forest.model_full_data.EF_full.rds` and noticed that names of the prediction tools appear as features (with `MeanDecreaseGini > 0`). In the EasyFuse publication, you described a model with smaller feature sets, operating independently of the prediction tools that showed slightly lower performance. Can you please provide access to this "_model with smaller feature sets_" ? 

```
# R
model_file = "Fusion_modeling_FFPE_train_v33.random_forest.model_full_data.EF_full.rds"
model <- readr::read_rds(model_file)
model$importance
                       MeanDecreaseGini
type                         73.7250814
exon_boundary                41.0677487
fusioncatcher_detected        0.5083960
infusion_detected             0.9841079
mapsplice_detected           10.8953450
soapfuse_detected            13.9531531
starfusion_detected           6.3734725
fusioncatcher_junc            0.0000000
infusion_junc                 0.0000000
mapsplice_junc                0.0000000
soapfuse_junc                 0.0000000
starfusion_junc               0.0000000
fusioncatcher_span            0.0000000
infusion_span                 0.0000000
mapsplice_span                0.0000000
soapfuse_span                 0.0000000
starfusion_span               0.0000000
tool_frac                    28.4812380
ft_a_best                    30.9791804
ft_b_best                    27.9950978
ft_junc_best                 36.5403701
wt1_junc_best                28.2912068
wt2_junc_best                24.8001392
ft_span_best                 64.0483935
wt1_span_best                32.1409714
wt2_span_best                24.5208664

```

Bit more context:
I run EasyFuse using an alternative config file (`--config-file ` parameter in `processing.py`) that lists a subset of gene-fusion callers (not all 5 default callers). Since the flexibility to choose which callers to run is baked into the source-code, EasyFuse completed the runs as I expected. However, since only a subset of callers is run as part of EasyFuse, I fear that model - `Fusion_modeling_FFPE_train_v33.random_forest.model_full_data.EF_full.rds` may not be valid for runs I submitted. I believe that the model "_with smaller feature sets_" would be the best fit for my analysis. So I'd be thankful if you can provide access to this model.

> From EasyFuse publication: "Two models with smaller feature sets, which operate independently of the prediction tools and provide more flexibility, achieved slightly lower performance (AUC, 0.88 versus 0.86)."

**Comment by ibn-salem** [comment]
Thanks for the request. The additional models are now provided in the `data/model` folder.

**Comment by PubuduSaneth** [comment]
Thank you very much @ibn-salem for sharing the additional models. Highly appreciate it 👍
