### ISSUE TITLE
Fusion caller versions in EasyFuse Docker container produce non-deterministic output

### ISSUE THREAD

**Issue by mobiusklein** [TRON-Bioinformatics/EasyFuse#33]
While testing EasyFuse's reproducibility on a test sample, we observed that `SOAPfuse`, `STARFusion` and `MapSplice2` gave different sets of fusion results when run on the same sample, on the same hardware, with the same parameters.

`STARFusion` has fixed this issue in a later release: https://github.com/STAR-Fusion/STAR-Fusion/issues/350. @Wan-Yifei did this work, and tested backporting the sorting function. 

`SOAPfuse` introduces inconsistencies during steps 1 and 2 (though there may be more). We were able to make the results consistent during step 1 by disabling threading, but this may not be enough to fix step 2. We couldn't find an issue tracker for `SOAPfuse` and the main group's website appears to be down. @jrouhana did this work.

We haven't been able to figure out why `MapSplice2` gives us different results. The author has not responded to our email yet. 

The `STARFusion` problem would be fixable by updating to a newer release, but it would require updating the index. We don't yet know how to fix the `SOAPfuse` issue.

Any advice would be appreciated.

**Comment by patricksorn** [comment]
Hi @mobiusklein ,

we are aware of the non-deterministic output of some of the tools which are dependant on Bowtie as aligner. We will keep this issue open for now, as it is not easily fixable respectively requires external parties involved.

For STARFusion we would have a look at this newer release.

Thanks a lot for your feedback!
