### ISSUE TITLE
EasyFuse skewer_wrapper.py problem

### ISSUE THREAD

**Issue by Kimgyeongjun** [TRON-Bioinformatics/EasyFuse#34]
(base) mas@binel229:~$ docker run --name easyfuse_container -v ~/tool/easyfuse_ref/:/ref -v ~/2021_RNA/FastqFile:/data -v ~/2021_RNA/fusion/:/output --rm -it tronbioinformatics/easyfuse:1.3.7 python /code/easyfuse/processing.py -i /data/ -o /output

Going to process the following read files...
Fastq file 0: /data/A11_R1.fastq.gz
Fastq file 1: /data/A11_R2.fastq.gz
Fastq file 2: /data/A12_R1.fastq.gz
Fastq file 3: /data/A12_R2.fastq.gz
Fastq file 4: /data/A1_R1.fastq.gz
Fastq file 5: /data/A1_R2.fastq.gz
Fastq file 6: /data/A2_R1.fastq.gz
Fastq file 7: /data/A2_R2.fastq.gz
Fastq file 8: /data/A3_R1.fastq.gz
Fastq file 9: /data/A3_R2.fastq.gz
Fastq file 10: /data/A4_R1.fastq.gz
Fastq file 11: /data/A4_R2.fastq.gz
Fastq file 12: /data/A5_R1.fastq.gz
Fastq file 13: /data/A5_R2.fastq.gz
Fastq file 14: /data/A6_R1.fastq.gz
Fastq file 15: /data/A6_R2.fastq.gz
Fastq file 16: /data/A7_R1.fastq.gz
Fastq file 17: /data/A7_R2.fastq.gz
Fastq file 18: /data/A8_R1.fastq.gz
Fastq file 19: /data/A8_R2.fastq.gz
Fastq file 20: /data/A9_R1.fastq.gz
Fastq file 21: /data/A9_R2.fastq.gz
Fastq file 22: /data/B10_R1.fastq.gz
Fastq file 23: /data/B10_R2.fastq.gz
Fastq file 24: /data/B11_R1.fastq.gz
Fastq file 25: /data/B11_R2.fastq.gz
Fastq file 26: /data/B12_R1.fastq.gz
Fastq file 27: /data/B12_R2.fastq.gz
Fastq file 28: /data/B1_R1.fastq.gz
Fastq file 29: /data/B1_R2.fastq.gz
Fastq file 30: /data/B2_R1.fastq.gz
Fastq file 31: /data/B2_R2.fastq.gz
Fastq file 32: /data/B3_R1.fastq.gz
Fastq file 33: /data/B3_R2.fastq.gz
Fastq file 34: /data/B4_R1.fastq.gz
Fastq file 35: /data/B4_R2.fastq.gz
Fastq file 36: /data/B5_R1.fastq.gz
Fastq file 37: /data/B5_R2.fastq.gz
Fastq file 38: /data/B6_R1.fastq.gz
Fastq file 39: /data/B6_R2.fastq.gz
Fastq file 40: /data/B7_R1.fastq.gz
Fastq file 41: /data/B7_R2.fastq.gz
Fastq file 42: /data/B8_R1.fastq.gz
Fastq file 43: /data/B8_R2.fastq.gz
Fastq file 44: /data/B9_R1.fastq.gz
Fastq file 45: /data/B9_R2.fastq.gz
Fastq file 46: /data/C10_R1.fastq.gz
Fastq file 47: /data/C10_R2.fastq.gz
Fastq file 48: /data/C11_R1.fastq.gz
Fastq file 49: /data/C11_R2.fastq.gz
Fastq file 50: /data/C12_R1.fastq.gz
Fastq file 51: /data/C12_R2.fastq.gz
Fastq file 52: /data/C1_R1.fastq.gz
Fastq file 53: /data/C1_R2.fastq.gz
Fastq file 54: /data/C2_R1.fastq.gz
Fastq file 55: /data/C2_R2.fastq.gz
Fastq file 56: /data/C3_R1.fastq.gz
Fastq file 57: /data/C3_R2.fastq.gz
Fastq file 58: /data/C4_R1.fastq.gz
Fastq file 59: /data/C4_R2.fastq.gz
Fastq file 60: /data/C5_R1.fastq.gz
Fastq file 61: /data/C5_R2.fastq.gz
Fastq file 62: /data/C6_R1.fastq.gz
Fastq file 63: /data/C6_R2.fastq.gz
Fastq file 64: /data/C7_R1.fastq.gz
Fastq file 65: /data/C7_R2.fastq.gz
Fastq file 66: /data/C8_R1.fastq.gz
Fastq file 67: /data/C8_R2.fastq.gz
Fastq file 68: /data/C9_R1.fastq.gz
Fastq file 69: /data/C9_R2.fastq.gz
Fastq file 70: /data/D10_R1.fastq.gz
Fastq file 71: /data/D10_R2.fastq.gz
Fastq file 72: /data/D11_R1.fastq.gz
Fastq file 73: /data/D11_R2.fastq.gz
Fastq file 74: /data/D12_R1.fastq.gz
Fastq file 75: /data/D12_R2.fastq.gz
Fastq file 76: /data/D1_R1.fastq.gz
Fastq file 77: /data/D1_R2.fastq.gz
Fastq file 78: /data/D2_R1.fastq.gz
Fastq file 79: /data/D2_R2.fastq.gz
Fastq file 80: /data/D3_R1.fastq.gz
Fastq file 81: /data/D3_R2.fastq.gz
Fastq file 82: /data/D4_R1.fastq.gz
Fastq file 83: /data/D4_R2.fastq.gz
Fastq file 84: /data/D5_R1.fastq.gz
Fastq file 85: /data/D5_R2.fastq.gz
Fastq file 86: /data/D6_R1.fastq.gz
Fastq file 87: /data/D6_R2.fastq.gz
Fastq file 88: /data/D7_R1.fastq.gz
Fastq file 89: /data/D7_R2.fastq.gz
Fastq file 90: /data/D8_R1.fastq.gz
Fastq file 91: /data/D8_R2.fastq.gz
Fastq file 92: /data/D9_R1.fastq.gz
Fastq file 93: /data/D9_R2.fastq.gz
Fastq file 94: /data/E10_R1.fastq.gz
Fastq file 95: /data/E10_R2.fastq.gz
Fastq file 96: /data/E11_R1.fastq.gz
Fastq file 97: /data/E11_R2.fastq.gz
Fastq file 98: /data/E12_R1.fastq.gz
Fastq file 99: /data/E12_R2.fastq.gz
Fastq file 100: /data/E1_R1.fastq.gz
Fastq file 101: /data/E1_R2.fastq.gz
Fastq file 102: /data/E2_R1.fastq.gz
Fastq file 103: /data/E2_R2.fastq.gz
Fastq file 104: /data/E3_R1.fastq.gz
Fastq file 105: /data/E3_R2.fastq.gz
Fastq file 106: /data/E4_R1.fastq.gz
Fastq file 107: /data/E4_R2.fastq.gz
Fastq file 108: /data/E5_R1.fastq.gz
Fastq file 109: /data/E5_R2.fastq.gz
Fastq file 110: /data/E6_R1.fastq.gz
Fastq file 111: /data/E6_R2.fastq.gz
Fastq file 112: /data/E7_R1.fastq.gz
Fastq file 113: /data/E7_R2.fastq.gz
Fastq file 114: /data/E8_R1.fastq.gz
Fastq file 115: /data/E8_R2.fastq.gz
Fastq file 116: /data/E9_R1.fastq.gz
Fastq file 117: /data/E9_R2.fastq.gz
Fastq file 118: /data/F10_R1.fastq.gz
Fastq file 119: /data/F10_R2.fastq.gz
Fastq file 120: /data/F11_R1.fastq.gz
Fastq file 121: /data/F11_R2.fastq.gz
Fastq file 122: /data/F12_R1.fastq.gz
Fastq file 123: /data/F12_R2.fastq.gz
Fastq file 124: /data/F1_R1.fastq.gz
Fastq file 125: /data/F1_R2.fastq.gz
Fastq file 126: /data/F2_R1.fastq.gz
Fastq file 127: /data/F2_R2.fastq.gz
Fastq file 128: /data/F3_R1.fastq.gz
Fastq file 129: /data/F3_R2.fastq.gz
Fastq file 130: /data/F4_R1.fastq.gz
Fastq file 131: /data/F4_R2.fastq.gz
Fastq file 132: /data/F5_R1.fastq.gz
Fastq file 133: /data/F5_R2.fastq.gz
Fastq file 134: /data/F6_R1.fastq.gz
Fastq file 135: /data/F6_R2.fastq.gz
Fastq file 136: /data/F7_R1.fastq.gz
Fastq file 137: /data/F7_R2.fastq.gz
Fastq file 138: /data/F8_R1.fastq.gz
Fastq file 139: /data/F8_R2.fastq.gz
Fastq file 140: /data/F9_R1.fastq.gz
Fastq file 141: /data/F9_R2.fastq.gz
Fastq file 142: /data/G10_R1.fastq.gz
Fastq file 143: /data/G10_R2.fastq.gz
Fastq file 144: /data/G11_R1.fastq.gz
Fastq file 145: /data/G11_R2.fastq.gz
Fastq file 146: /data/G12_R1.fastq.gz
Fastq file 147: /data/G12_R2.fastq.gz
Fastq file 148: /data/G1_R1.fastq.gz
Fastq file 149: /data/G1_R2.fastq.gz
Fastq file 150: /data/G2_R1.fastq.gz
Fastq file 151: /data/G2_R2.fastq.gz
Fastq file 152: /data/G3_R1.fastq.gz
Fastq file 153: /data/G3_R2.fastq.gz
Fastq file 154: /data/G4_R1.fastq.gz
Fastq file 155: /data/G4_R2.fastq.gz
Fastq file 156: /data/G5_R1.fastq.gz
Fastq file 157: /data/G5_R2.fastq.gz
Fastq file 158: /data/G6_R1.fastq.gz
Fastq file 159: /data/G6_R2.fastq.gz
Fastq file 160: /data/G7_R1.fastq.gz
Fastq file 161: /data/G7_R2.fastq.gz
Fastq file 162: /data/G8_R1.fastq.gz
Fastq file 163: /data/G8_R2.fastq.gz
Fastq file 164: /data/G9_R1.fastq.gz
Fastq file 165: /data/G9_R2.fastq.gz
Fastq file 166: /data/H10_R1.fastq.gz
Fastq file 167: /data/H10_R2.fastq.gz
Fastq file 168: /data/H11_R1.fastq.gz
Fastq file 169: /data/H11_R2.fastq.gz
Fastq file 170: /data/H12_R1.fastq.gz
Fastq file 171: /data/H12_R2.fastq.gz
Fastq file 172: /data/H1_R1.fastq.gz
Fastq file 173: /data/H1_R2.fastq.gz
Fastq file 174: /data/H2_R1.fastq.gz
Fastq file 175: /data/H2_R2.fastq.gz
Fastq file 176: /data/H3_R1.fastq.gz
Fastq file 177: /data/H3_R2.fastq.gz
Fastq file 178: /data/H4_R1.fastq.gz
Fastq file 179: /data/H4_R2.fastq.gz
Fastq file 180: /data/H5_R1.fastq.gz
Fastq file 181: /data/H5_R2.fastq.gz
Fastq file 182: /data/H6_R1.fastq.gz
Fastq file 183: /data/H6_R2.fastq.gz
Fastq file 184: /data/H7_R1.fastq.gz
Fastq file 185: /data/H7_R2.fastq.gz
Fastq file 186: /data/H8_R1.fastq.gz
Fastq file 187: /data/H8_R2.fastq.gz
Fastq file 188: /data/H9_R1.fastq.gz
Fastq file 189: /data/H9_R2.fastq.gz
A11 ['NA']
/output/Sample_A11/filtered_reads/out_file-trimmed-pair1_filtered.fastq /output/Sample_A11/filtered_reads/out_file-trimmed-pair2_filtered.fastq
Running EasyFuse-qc-A11_CMD0
CMD: fastqc --nogroup --extract -t 6 -o /output/Sample_A11/qc /data/A11_R1.fastq.gz /data/A11_R2.fastq.gz
Running EasyFuse-qc-A11_CMD1
CMD: /code/miniconda3/bin/python /code/easyfuse/misc/qc_parser.py -i /output/Sample_A11/qc/A11_R1_fastqc/fastqc_data.txt /output/Sample_A11/qc/A11_R2_fastqc/fastqc_data.txt -o /output/Sample_A11/qc/qc_table.txt
Running EasyFuse-qc-A11_CMD2
CMD: /code/miniconda3/bin/python /code/easyfuse/tool_wrapper/skewer_wrapper.py -q /output/Sample_A11/qc/qc_table.txt -i /data/A11_R1.fastq.gz /data/A11_R2.fastq.gz -o /output/Sample_A11/qc/skewer -b /code/skewer-0.2.2/skewer -m 0.75
Error: Command "['/code/miniconda3/bin/python', '/code/easyfuse/tool_wrapper/skewer_wrapper.py', '-q', '/output/Sample_A11/qc/qc_table.txt', '-i', '/data/A11_R1.fastq.gz', '/data/A11_R2.fastq.gz', '-o', '/output/Sample_A11/qc/skewer', '-b', '/code/skewer-0.2.2/skewer', '-m', '0.75']" returned non-zero exit status
b"Trim length too long. Discarding fastqs (['/data/A11_R1.fastq.gz', '/data/A11_R2.fastq.gz'])."

> Hello I have a question about the EasyFuse. What is my problem? I did 150bp illumina sequencing. In the literature, there is only 50bp sequencing. Is the problem with the read length??

**Comment by patricksorn** [comment]
Hi @Kimgyeongjun ,

It seems that your Fastqs fall below out quality trimming threshold and are therefore excluded from further analysis. 
You could circumvent this by using your own config file for your docker run. You can do so by downloading the config.ini.docker from the main repository (https://github.com/TRON-Bioinformatics/EasyFuse/blob/master/config.ini.docker) and update `min_read_len_perc = 0.75 -> 0.0`. This parameter defines the minimum read length required for further processing after quality trimming.

Thanks for the feedback and I hope the proposed solution will be sufficient.

**Comment by BGI2016** [comment]
Hi @patricksorn ，
I have the same problem. How to use my own config file for my docker run? Can you give me an example?Thanks.
