### ISSUE TITLE
Fresh frozen RNAseq compatible with prediction model？

### ISSUE THREAD

**Issue by Tesson98** [TRON-Bioinformatics/EasyFuse#38]
Hi @ibn-salem,
     I recently noticed in the related paper that the machine learning prediction model was trained by FFPE samples. However, all my RNAseq were derived from Fresh frozen (FF) tumor biopsies.
     So I worried if I can apply this machine learning model on my FF samples?
     If not, is there any possibility you add a prediction model training with FF samples in new versions? 
     Hope for your suggestions.
     Thank you!

Tesson,
21st, Feb, 2023

**Comment by ibn-salem** [comment]
Hi @Tesson98, 
thanks for your question. We did not tested it systematically, but the models should in principle also work on FF samples.
