### ISSUE TITLE
FASTQ input

### ISSUE THREAD

**Issue by gitMakeCoffee** [TRON-Bioinformatics/EasyFuse#40]
I'm very excited to try out EasyFuse on some sequencing data.
Do the input FASTQ files need to be preprocessed before injection into EasyFuse? 
Or should I just provide raw out-of-the-sequencer FASTQs?
Any recommendations regarding CPU/Mem for 1 pair of paired-end FASTQs?
Thanks.

**Comment by patricksorn** [comment]
Dear @gitMakeCoffee ,

you can provide the raw out-of-the-sequencer FASTQs as input. There will be internal preprocessing.
CPU/Mem consumption highly depends on the size of your input FASTQ pair. 
But a good limit would be 50GB of memory @ 12 cores. Increase the numbers if required.

Best regards,
Patrick
