### ISSUE TITLE
Support for CHM13

### ISSUE THREAD

**Issue by gitMakeCoffee** [TRON-Bioinformatics/EasyFuse#41]
Are there plans to support the new T2T genome assembly? Thanks.

**Comment by patricksorn** [comment]
Hi @gitMakeCoffee ,

good point! So far there are no plans to integrate/support the new T2T. We would also require the tools integrated into EasyFuse support the T2T genome assembly first, as most of them are currently based on GRCh38 . The only support for T2T has Starfusion, as far as I know.

Best regards,
Patrick
