### ISSUE TITLE
about version 1.3.7

### ISSUE THREAD

**Issue by BGI2016** [TRON-Bioinformatics/EasyFuse#43]
Dear author, 

when I used the latest version 1.3.7 of easyfuse, I found that some published MCF7 and SKBR3 cell line positive fusions were predicted to be negative, while version 1.3.6 were predicted to be positive.According to my data form published MCF7 and SKBR3 cell line fusions , it seems that the TPR of 1.3.6 is higher than that of 1.3.7？

**Comment by ibn-salem** [comment]
Hi, thanks for letting us know. We only analyzed the performance of version 1.3.7 in the FFPE test samples. So yes, it is possible that 1.3.7 gives different results compared to 1.3.6 for some fusions in MCF7 and SKBR3.
