### ISSUE TITLE
tool_count==0 in the fusRank_1.csv output

### ISSUE THREAD

**Issue by p-levy** [TRON-Bioinformatics/EasyFuse#5]
Dear easyfuse authors, 

Thanks for sharing this tool with the community! 

I have one question regarding some fusion genes reported in the `fusRank_1.csv` output but not reported to be detected by any of the tool (`total_count` column shows `0`). How to interpret that? Could these fusions still be real or they are probably artefacts? 

Best,
Pierre

**Comment by ibn-salem** [comment]
Hi, yes, we are aware of this issue. The `tool_count` column is currently not correct. Each reported gene fusion was predicted by at least one tool. A fix for this is currently implemented in the branch `change_to_bpid` and might be part of the next release.

**Comment by patricksorn** [comment]
@p-levy This issue should be resolved in our new release v1.3.5. Please give it a try.

**Comment by ibn-salem** [comment]
This should be resolved in the latest versions so I will close this issue.
