### ISSUE TITLE
Typo in QC workflow

### ISSUE THREAD

**Issue by joelnulsen** [TRON-Bioinformatics/EasyFuse#51]
Thank you for releasing version 2!

I discovered what is probably a typo. [Line 43 of `modules/01_qc.nf`](https://github.com/TRON-Bioinformatics/EasyFuse/blob/7ecc666dca549acac1bda008f29b83e2ac07996d/modules/01_qc.nf#L43C1-L43C50) currently reads 

`easy-fuse qc-parser -i $fastq1_qc_data $fastq1_qc_data -o qc_table.txt`

which uses the mate 1 FASTQ twice, rather than mate 1 and mate 2. So it should probably be

`easy-fuse qc-parser -i $fastq1_qc_data $fastq2_qc_data -o qc_table.txt`

Cheers,
Joel

**Comment by ibn-salem** [comment]
Hi @joelnulsen, 
many thanks for reporting this. We will try to fix it as soon as possible. 
Best,
Jonas

**Comment by patricksorn** [comment]
Fixed this issue in release 2.0.1
