### ISSUE TITLE
Supporting Reads Number

### ISSUE THREAD

**Issue by Tesson98** [TRON-Bioinformatics/EasyFuse#53]
Hi!
I have run EasyFuse version 1.3.6 with my ~700 tumor bulk RNA-seq sample and filtered some inspiring fusion results. 
It would be helpful to get the supporting reads number for each fusion result thus I can choose some to validate first. 
With the released versions of EasyFuse, can I get the supporting reads in outputs?  
If not,  any suggestions about getting supporting reads would be grateful.
Thank you so much!

Tesson,
Shanghai Jiao Tong University,
September 18th, 2023.

**Comment by ibn-salem** [comment]
Please try with the latest version of EasyFuse.
