### ISSUE TITLE
Download reference archive

### ISSUE THREAD

**Issue by onurtugalan** [TRON-Bioinformatics/EasyFuse#54]
Hello,

First of all congrats for the tool, it looks super interesting and cannot wait to test it.

I am going to use v1.3.7 and tried downloading the references with the command which you provided in the documentation but it doesnt work. Is there something wrong with the ftp server at the moment? And if so is there any other way i can get this references ? Otherwise i will have to download all by myself.

I tried the following commands

wget ftp://easyfuse.tron-mainz.de/easyfuse_ref_v3.tar.gz
wget http://easyfuse.tron-mainz.de/easyfuse_ref_v3.tar.gz

**Comment by patricksorn** [comment]
Hi @onurtugalan ,

for v1.3.7 you have to use v2 of the reference:
wget ftp://easyfuse.tron-mainz.de/easyfuse_ref_v2.tar.gz
It contains the reference to all 5 tools being used in the pipeline.
I think it was a bit misleading in the README.

**Comment by onurtugalan** [comment]
Thanks,problem solved
