### ISSUE TITLE
Error installing with pip inside conda environment

### ISSUE THREAD

**Issue by abalter** [TRON-Bioinformatics/EasyFuse#6]
(base) balter@spectre:\~$ conda create -n easyfuse pip -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

...
...

(base) balter@spectre:\~$ conda activate easyfuse
(easyfuse) balter@spectre:\~$ which pip
/home/balter/conda/envs/easyfuse/bin/pip
(easyfuse) balter@spectre:\~$ pip install easyfuse
Collecting easyfuse
  Using cached easyfuse-0.0.1.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... done
Collecting llfuse
  Using cached llfuse-1.4.2.tar.gz (834 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 2
  ╰─> [4 lines of output]
      Package fuse was not found in the pkg-config search path.
      Perhaps you should add the directory containing `fuse.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'fuse' found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ibn-salem** [comment]
Dear @abalter,

EasyFuse cannot be installed with `pip install easyfuse` as it is not in PyPI. The command installes a different python package which is not related to this repository. 
Please use docker or singularity to run EasyFuse as described in the README. 
Thank you.
