### ISSUE TITLE
Differences between the reference output and ours with the demo data SRR41659960_05pc

### ISSUE THREAD

**Issue by TianShuangJ** [TRON-Bioinformatics/EasyFuse#7]
Dear  @ibn-salem @priesgo and whom may concern,
    Thanks for the release of EasyFuse_1.3.4, which I sincerely considered as a powerful tool for gene fusions research.
    Here when we tested the pipeline with the singularity image of EasyFuse_1.3.4 and the demo fastq data 'SRR41659960_05pc' in our school HPC platform, we found our output file was different with the reference output file. 
    In brief, there were 339 fusion calls in the reference but 421 in our output. And the *_junc or *_span columns were all 0s in our output.
   The reference output and our output files were in the followings：
   [SRR1659960_05pc_fusRank_1.csv](https://github.com/TRON-Bioinformatics/EasyFuse/files/8864066/SRR1659960_05pc_fusRank_1.csv)
   [SRR1659960_05pc_refOut.csv](https://github.com/TRON-Bioinformatics/EasyFuse/files/8864068/SRR1659960_05pc_refOut.csv)
    Do you have some suggestions? Are the differences normal? Thanks a lot!
 
Yours,
Tesson

**Comment by priesgo** [comment]
@patricksorn ping

**Comment by ibn-salem** [comment]
Dear @TianShuangJ ,

the example output files were outdated and are now updated in the latest version of EasyFuse. Can you please try if you can reproduce the same output files? 

Thank you!

**Comment by TianShuangJ** [comment]
@ibn-salem 

Thanks for the update of version 1.3.6. 
Now when I tested the pipeline with the test case , my output was the same as the refout.
Thanks again and wish you and your group more achivements.
 
Yours,
Tesson
